config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :posts
  resources :users, only: [:index, :show]

  resources :chats do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
    belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, :scope => :recipient_id
    
    scope :between_sender_and, -> (sender_id,recipient_id) do
        where(sender_id: sender_id, recipient_id: recipient_id)
    end
    scope :between, -> (u_id_1, u_id_2) { between_sender_and(u_id_1, u_id_2) + between_sender_and(u_id_2, u_id_1) }
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :chat
    belongs_to :user
    validates_presence_of :body, :chat_id, :user_id
    
    def message_time
     created_at.strftime('%m/%d/%y at %l:%M')
    end
end

app/models/post.rb
class Post < ApplicationRecord
    # validates :price, presence: true
    belongs_to :user  
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, :dependent => :delete_all
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

    before_action :authenticate_user!

    def index
        @users = User.all
        @chats = Chat.all
    end

    def create
        if Chat.between(params[:sender_id],params[:recipient_id]).present?
            @chat = Chat.between(params[:sender_id],
            params[:recipient_id]).first
        else
            @chat= Chat.create!(chat_params)
        end
        redirect_to chat_messages_path(@chat)
    end

    private
    def chat_params
        params.permit(:sender_id, :recipient_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    
    before_action do
        @chat = Chat.find(params[:chat_id])
    end

    def index
        @messages = @chat.messages
        if @messages.length > 10
            @over_ten = true
            @messages = @messages[-10..-1]
        end
        if params[:m]
            @over_ten = false
            @messages = @chat.messages
        end
        if @messages.last
            if @messages.last.user_id != current_user.id
                @messages.last.read = true;
            end
        end
        @message = @chat.messages.new
    end
  
    def new
        @message = @chat.messages.new
    end
  
    def create
        @message = @chat.messages.new(message_params)
        if @message.save
            redirect_to chat_messages_path(@chat)
        end
    end
    
    private
    
    def message_params
        params.require(:message).permit(:body, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
            redirect_to @post
            flash[:notice] = "Post created successfully"
        else
            redirect_to :posts
            flash[:alert] = "Post creation has failed."
        end
    end

    def edit
        @post = Post.find(params[:id])
        if current_user != @post.user
            sign_out current_user
            redirect_to "/"
            flash[:alert] = "Unauthorized request"
        end
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to @post
            flash[:notice] = "Post has been updated!"
        else
            redirect_back(fallback_location[root_path])
            flash[:alert] = "Post update has failed."
        end
    end

    def destroy
        post = Post.find(params[:id])
        if current_user = post.user
            post.destroy
            redirect_to "/posts"
            flash[:notice] = "Post Deleted"
        else
            redirect_back(fallback_location: root_path)
            flash[:alert] = "Not Authoried to Delete Post"
        end
    end

    private
    def post_params
        params.require(:post).permit(:price, :title, :description, :image) 
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :location, :user_quote, :user_description, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :location, :user_quote, :user_description, :avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :location, :user_quote, :user_description) 
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :check_signed_in

  def index
  end

  def check_signed_in
    redirect_to '/posts' if signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
      end
    
      def resource_class 
         User 
      end
    
      def resource
        @resource ||= User.new
      end
    
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chats/index.html.erb
<div class="chats-container">    

    <div class=”ui segment”><br>
        <h3 class="mail-title">Mailbox</h3><br>
        <div class=”ui list”>
            <div class=”item”>
                <% @chats.each do |chat| %>
                    <% if chat.sender_id == current_user.id || chat.recipient_id == current_user.id %>
                            <% if chat.sender_id == current_user.id %>
                                <% recipient = User.find(chat.recipient_id) %>
                            <% else %>
                                <% recipient = User.find(chat.sender_id) %>
                            <% end %>
                        <%= link_to recipient.username, chat_messages_path(chat)%><br>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div><br><br>

    <div class=”ui segment”>
        <h3 class="mail-title">All Users</h3><br>
        <div class=”ui list”>
            <% @users.each do |user| %>
                <% if user.id != current_user.id %>
                    <div class=”item”>
                        <%= user.username %> <%= link_to 'Message me!', chats_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>TwoWheeledBS</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <!-- Bootstrap Link -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

    <body class="background">

        <div class="navbar navbar-text">

            <div class="container-fluid" style="justify-content: flex-end">
                <% if user_signed_in? %>
                    <%= image_tag "moto-man-mint.png", class: "moto-man-lite" %>
                    <ul class="nav-ul">
                        <li class="nav-item">
                            <a><%= link_to "Posts", "/posts", class: "navbar-link" %></a>
                        </li>
                        <li class="nav-item">
                            <a><%= link_to "New Post", "/posts/new", class: "navbar-link" %></a>
                        </li>
                        <li class="nav-item">
                            <a><%= link_to 'Inbox', "/chats", class: "navbar-link" %></a>
                        </li>
                        <li class="nav-item">
                            <a><%= link_to 'Edit Profile', edit_user_registration_path, class: "navbar-link" %></a>
                        </li>
                        <li class="nav-item">
                            <a><%= link_to "Logout", destroy_user_session_path, class: "navbar-link", method: :delete %></a>
                        </li>
                        <li class="nav-item">
                            <% if current_user.avatar.attached? %>
                                <a><%= link_to(image_tag(current_user.avatar, class: "navbar-avatar"), "/users/#{current_user.id}") %></a>
                            <% end %>
                        </li>
                    </ul>

                <% else %>

                    <ul>
                        <li>
                            <a class="nav-link"><%= link_to "Two-Wheeled Buy & Sell", "/", class: "navbar-logo" %></a>
                        </li>
                    </ul>
                <% end %>
            </div>
        </div>

        <%= yield %>
        </div>

    </body>
</html>

app/views/messages/index.html.erb
<div class="mailbox-container"> 
    <br><% if @over_ten %>
        <%= link_to 'Show Previous', '?m=all' %>
    <% end %><br>

    <div class=”ui message-container segment”>
        <% @messages.each do |message| %>
            <% if message.body %>
                <% user = User.find(message.user_id) %>
                <div class=”item”>
                    <div class=”message-content”>
                        <div class=”header”><strong><%= user.username %></strong> sent at <%= message.message_time %></div>
                        <div class=”list”>
                            <div class=”mailbox-item”>
                                <i class=”right triangle icon”></i>
                                <%= message.body %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div><br>

    <%= form_for [@chat, @message], html: {class: 'ui reply form'} do |f| %>
        <div class='field'>
            <%= f.text_area :body, class: 'form-control' %>
        </div>
        <%= f.text_field :user_id, value: current_user.id, type: 'hidden' %><br>
        <div class="mailbox-reply-button">
            <%= f.submit 'Send Message', class: 'ui blue labeled submit icon button' %>
        </div>
    <% end %>
</div>     

app/views/posts/edit.html.erb
<div class="edit-form">
    <h1>Edit Post</h1><br>
    <%= form_with model: @post do |f| %>
        <div>
            <p class="post-update-text-1">Price: </p>
            <%= f.text_area :price, required: true %>
        </div><br>
        <div>
            <p class="post-update-text-2">Title:</p>
            <%= f.text_area :title, required: true %>
        </div><br>
        <div>
            <p class="post-update-text-3">Description: </p>
            <%= f.text_area :description, required: true %>
        </div>
        <br>
        <%= f.submit %>
    <% end %>
</div>

app/views/posts/index.html.erb
<h1 class="posts-title">Recent Posts</h1><br>

<div class="container">
    <% @posts.reverse.each do |post| %>
        <div class="card">
            <div class="card-img-top"><%= link_to(image_tag(post.image, class: "card-img"), post) %></div>
            <div class="card-body">
                <h3><%= link_to post.title, "/posts/#{post.id}", class: "card-title" %></h3>
                <p class="card-text">$<%= post.price %></p>
                <div class="user-info">
                    <div class="card-img"><%= link_to(image_tag(post.user.avatar, class: "avatar"), "/users/#{post.user.id}") %></div>
                    <p><%= link_to post.user.username, post.user, class: "card-username" %></p>
                </div>
            </div>
        </div>
    <% end %>   
</div>

app/views/posts/new.html.erb
<div class="edit-form">
  <h1 >New Post</h1><br><br>
    <%= form_with model: @post do |f| %>
      <p>
        <%= f.label :price, class: "edit-user-text-1" %><br>
        <%= f.number_field(:price, required: true) %>
      </p>
    
      <p>
        <%= f.label :title, class: "edit-user-text-2" %><br>
        <%= f.text_field :title, required: true %>
      </p>

      <p>
        <%= f.label :description, class: "edit-user-text-3" %><br>
        <%= f.text_area :description, required: true %>
      </p>

      <p>
        <%= f.label :image, class: "edit-user-text-4" %>
        <%= f.file_field :image %>
      </p><br
      
      <p>
        <%= f.submit %>
      </p>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
    <div>
        <h1 class="posts-title"><%= @post.title %></h1>
        <h3 class="posts-text">Price posted: $<%= @post.price %></h3>
        <h3 class="posts-text">Seller: <%= link_to @post.user.username, "/users/#{@post.user.id}", class: "post-texts" %>     <%= image_tag @post.user.avatar, class: "avatar" %></h3>
        <h3 class="posts-text">Item location: <%= @post.user.location %></h3><br>
        <h3 class="posts-text">Send <%= link_to "#{@post.user.username}", chats_path(sender_id: current_user.id, recipient_id: @post.user.id), method: :post %> a message.</h3><br>
        <p class="text"><strong>Item description: </strong><%= @post.description %></p>
        <div class="post-id">
            <%= image_tag @post.image, class: "post-img" %>
        </div>
        <div class="post-buttons">
            <% if current_user == @post.user %>
                <div class="post-delete">
                    <%= button_to "Delete", @post, method: :delete %>
                </div>
                <div class="post-edit">
                    <%= link_to "Edit", "/posts/#{@post.id}/edit?" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

    

app/views/users/index.html.erb
<br><h1>Two-Wheeled B/S Users</h1><br><br>

<% @users.each do |user| %>
    <div>Username: <%= link_to user.username, "/users/#{user.id}" %></div>
    <div>Location: <%= user.location %></div>
    <div>Quote: <%= user.user_quote %></div>
    <div>Description: <%= user.user_description %></div>
    <div>Number of Posts:<%= user.posts.length %></div><br><br><br>
<% end %>

app/views/users/show.html.erb
<div class="users-show-container">
    <div>
        <h1 class="user-show-title"><%= "Meet #{@user.username}"%></h1><br>
        <div class="user-show-info">
            <div class="user-show-avatar">
                <%= image_tag @user.avatar, class: "avatar-userpage" %>
            </div>
            <div class="user-show-info-block">
                <h3 class="user-show-text">Username: <%= @user.username  %></h3>
                <h3 class="user-show-text">Location: <%= @user.location %></h3>
                <h3 class="user-show-text">Quote: <%= @user.user_quote %></h3>
                <h4 class="user-show-text">A little bit about <%= @user.username%>: <%= @user.user_description %></h4>
                <h3 class="user-show-text">Post counter: <%= @user.posts.length %></h3><br>
            </div>
        </div>
    </div>

    <h1 class="user-show-title"><%= @user.username %>'s Posts:</h1>
    
    <div class="user-show-posts-container"> 
        <% @user.posts.each do |post| %>
            <div class="user-showcard">
                <div>
                    <a href="<%= "/posts/#{post.id}" %>">
                        <div>
                            <%= link_to(image_tag(post.image, class: "user-show-post-images"), post) %>
                        </div>
                    </a>
                </div>
                <div class="user-show-post-text-box">
                    <h3 class="user-show-post-title"><strong><%= link_to post.title, post %></strong></h3><br>
                    <h3 class="user-show-post-text-loc"><strong><%= post.user.location %></strong></h3>
                    <p class="user-show-post-text"><%= post.description %></p>
                    <div class="user-show-post-bottom">   
                        <div class="user-show-post-button-box">
                            <% if current_user == post.user %>
                                <%= button_to "Delete", post, method: :delete %>
                                <%= link_to "Edit", edit_post_path %>
                            <% end %> 
                        </div>
                        <div class="user-show-post-price-box"> 
                            <h3 class="user-show-post-price">$<%= post.price %></h3>
                        </div>
                    </div>
                </div>    
            </div>
        <% end %>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="opening-container">
    <%= image_tag "moto-man-final.png", class: "moto-man-logo" %>
    <div class="opening-block">
        <div class="welcome-text">
            <h3 class="welcome-text-1">Welcome to</h3>
            <h1 class="welcome-text-2">Two-Wheeled Buy & Sell</h1>

            <h3 class="welcome-text-3">The online marketplace for new, used and  custom motorcycle parts and accessories</h3>
        </div>

        <div class="welcome-buttons">
            <%= button_to "Sign Up", "/users/sign_up", method: :get, class: "sign-up-button" %>
            <%= button_to "Sign In", "/users/sign_in", method: :get, class: "sign-in-button" %>
        </div>
    </div>
</div>